services:
  api-server:
    build: ./app
    image: spring-boot-backend:latest
    expose:
      - "8080"

  web-client:
    build: ./frontend
    image: angular-frontend:latest
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://api-server:8080
    depends_on:
      - api-server